services:
  app:
    build: ./
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - SURREAL_URI=ws://surrealdb:9000/rpc
      - NODE_ENV=production
    networks:
      - surrealdb-net
    volumes:
      - ~/Accounts/avatars:/app/avatars

networks:
  surrealdb-net:
    name: surrealdb-net
    driver: bridge
    external: true